version: '3.3'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: "db"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    expose:
      - "5432"
    env_file: ./.env
    volumes:
      - /var/lib/postgresql/data/
  redis:
    image: redis:6-alpine
    depends_on: 
      - db
    expose:
      - "6379"
  web:
    restart: always
    build: .
    command: gunicorn test_kanalservice.wsgi:application --workers=5 --bind 0.0.0.0:8000
    volumes: 
      - static_value:/app/static/
      - media_value:/app/media/
      - ./logs:/app/logs/
    env_file: ./.env
    depends_on: 
      - redis
  celery:
    build: ./
    command: celery -A test_kanalservice worker -l INFO -B -Q get_position_queue,celery --logfile=logs/celery.log
    volumes: 
      - static_value:/app/static/
      - media_value:/app/media/
      - ./logs:/app/logs/
    env_file: ./.env
    depends_on: 
      - web
  nginx:
    image: nginx:1.19.3
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - web
volumes:
  postgres_data:
  static_value:
  media_value: